apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "myapp.example.com/v1alpha1",
          "kind": "MyApp",
          "metadata": {
            "name": "example-myapp",
            "namespace": "default"
          },
          "spec": {
            "replicas": 3
          }
        }
      ]
    capabilities: Basic Install
  name: myapp-operator.v0.0.8
<<<<<<< HEAD
  namespace: openshift-marketplace 
=======
  namespace: placeholder
>>>>>>> b7e779cd75bc79a5832d93c153672ce87c540639
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MyApp is the Schema for the myapps API
      kind: MyApp
      name: myapps.myapp.example.com
      version: v1alpha1
  description: myapp
  displayName: myapp-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments:
      - name: myapp-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: myapp-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: myapp-operator
            spec:
              containers:
              - command:
                - myapp-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: myapp-operator
                image: quay.io/huzefa51/myapp-operator:latest
                imagePullPolicy: Always
                name: myapp-operator
                resources: {}
              serviceAccountName: myapp-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - myapp-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - myapp.example.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: myapp-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - myapp
  links:
  - name: Myapp Operator
    url: https://myapp-operator.domain
  maintainers:
  - email: huzefa.hamdard53@gmail.com
    name: huzefa
  maturity: alpha
  provider:
    name: huzefa
  version: 0.0.8
