apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-operator
  namespace: openshift-marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myapp-operator
  template:
    metadata:
      labels:
        name: myapp-operator
    spec:
      serviceAccountName: myapp-operator
      containers:
        - name: myapp-operator
          # Replace this with the built image name
          image: quay.io/huzefa51/myapp-operator:latest
          command:
          - myapp-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "myapp-operator"
